parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: ./tsconfig.json
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
plugins:
  - "@typescript-eslint"
env:
  node: true
  mocha: true
rules:
  "@typescript-eslint/no-explicit-any": "off"
  "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }]
  "@typescript-eslint/explicit-module-boundary-types": "off"
  "@typescript-eslint/no-non-null-assertion": "off"

