printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
quoteProps: "as-needed"
trailingComma: "es5"
bracketSpacing: true
arrowParens: "always"
overrides:
  - files: "*.sol"
    options:
      printWidth: 120
      tabWidth: 4
      singleQuote: false

