/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FHEJunctionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "applications"
      | "applyForJob"
      | "companies"
      | "confidentialProtocolId"
      | "createJob"
      | "evaluateAllApplicants"
      | "individuals"
      | "jobs"
      | "nextJobId"
      | "registerCompany"
      | "registerIndividual"
      | "updateCompanyProfile"
      | "updateIndividualProfile"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ApplicantEvaluated"
      | "ApplicationSubmitted"
      | "CompanyProfileUpdated"
      | "CompanyRegistered"
      | "IndividualProfileUpdated"
      | "IndividualRegistered"
      | "JobCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "applications",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "applyForJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "companies",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createJob",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "evaluateAllApplicants",
    values: [BigNumberish, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "individuals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "jobs", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "nextJobId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerCompany",
    values: [string, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerIndividual",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCompanyProfile",
    values: [string, string, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateIndividualProfile",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "applications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyForJob",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "companies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "evaluateAllApplicants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "individuals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextJobId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerCompany",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerIndividual",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCompanyProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateIndividualProfile",
    data: BytesLike
  ): Result;
}

export namespace ApplicantEvaluatedEvent {
  export type InputTuple = [jobId: BigNumberish, applicant: AddressLike];
  export type OutputTuple = [jobId: bigint, applicant: string];
  export interface OutputObject {
    jobId: bigint;
    applicant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApplicationSubmittedEvent {
  export type InputTuple = [jobId: BigNumberish, applicant: AddressLike];
  export type OutputTuple = [jobId: bigint, applicant: string];
  export interface OutputObject {
    jobId: bigint;
    applicant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CompanyProfileUpdatedEvent {
  export type InputTuple = [company: AddressLike, name: string];
  export type OutputTuple = [company: string, name: string];
  export interface OutputObject {
    company: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CompanyRegisteredEvent {
  export type InputTuple = [company: AddressLike, name: string];
  export type OutputTuple = [company: string, name: string];
  export interface OutputObject {
    company: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IndividualProfileUpdatedEvent {
  export type InputTuple = [individual: AddressLike, version: BigNumberish];
  export type OutputTuple = [individual: string, version: bigint];
  export interface OutputObject {
    individual: string;
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IndividualRegisteredEvent {
  export type InputTuple = [individual: AddressLike];
  export type OutputTuple = [individual: string];
  export interface OutputObject {
    individual: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCreatedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    company: AddressLike,
    title: string
  ];
  export type OutputTuple = [jobId: bigint, company: string, title: string];
  export interface OutputObject {
    jobId: bigint;
    company: string;
    title: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHEJunction extends BaseContract {
  connect(runner?: ContractRunner | null): FHEJunction;
  waitForDeployment(): Promise<this>;

  interface: FHEJunctionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  applications: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        string,
        string,
        string,
        boolean,
        boolean
      ] & {
        salary: string;
        experience: string;
        education: string;
        sex: string;
        profileVersion: bigint;
        contactEmail: string;
        contactPhone: string;
        eligible: string;
        evaluated: boolean;
        applied: boolean;
      }
    ],
    "view"
  >;

  applyForJob: TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;

  companies: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, string, string, boolean] & {
        name: string;
        industry: string;
        website: string;
        contactEmail: string;
        location: string;
        owner: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createJob: TypedContractMethod<
    [
      title: string,
      location: string,
      workPreference: BigNumberish,
      primaryField: BigNumberish,
      extMaxSalary: BytesLike,
      extMinExperience: BytesLike,
      extMinEducation: BytesLike,
      extPreferredSex: BytesLike,
      attestation: BytesLike,
      applicationDeadline: BigNumberish,
      vacancyCount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  evaluateAllApplicants: TypedContractMethod<
    [jobId: BigNumberish, applicants: AddressLike[]],
    [void],
    "nonpayable"
  >;

  individuals: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, string, string, bigint, boolean] & {
        expectedSalary: string;
        experience: string;
        education: string;
        sex: string;
        contactEmail: string;
        contactPhone: string;
        version: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  jobs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        company: string;
        title: string;
        location: string;
        workPreference: bigint;
        primaryField: bigint;
        maxSalary: string;
        minExperience: string;
        minEducation: string;
        preferredSex: string;
        applicationDeadline: bigint;
        vacancyCount: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  nextJobId: TypedContractMethod<[], [bigint], "view">;

  registerCompany: TypedContractMethod<
    [
      name: string,
      industry: string,
      website: string,
      contactEmail: string,
      location: string
    ],
    [void],
    "nonpayable"
  >;

  registerIndividual: TypedContractMethod<
    [
      extSalary: BytesLike,
      extExperience: BytesLike,
      extEducation: BytesLike,
      extSex: BytesLike,
      extContactEmail: BytesLike,
      extContactPhone: BytesLike,
      attestation: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  updateCompanyProfile: TypedContractMethod<
    [
      name: string,
      industry: string,
      website: string,
      contactEmail: string,
      location: string
    ],
    [void],
    "nonpayable"
  >;

  updateIndividualProfile: TypedContractMethod<
    [
      extSalary: BytesLike,
      extExperience: BytesLike,
      extEducation: BytesLike,
      extSex: BytesLike,
      extContactEmail: BytesLike,
      extContactPhone: BytesLike,
      attestation: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "applications"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        string,
        string,
        string,
        boolean,
        boolean
      ] & {
        salary: string;
        experience: string;
        education: string;
        sex: string;
        profileVersion: bigint;
        contactEmail: string;
        contactPhone: string;
        eligible: string;
        evaluated: boolean;
        applied: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "applyForJob"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "companies"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, string, string, boolean] & {
        name: string;
        industry: string;
        website: string;
        contactEmail: string;
        location: string;
        owner: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createJob"
  ): TypedContractMethod<
    [
      title: string,
      location: string,
      workPreference: BigNumberish,
      primaryField: BigNumberish,
      extMaxSalary: BytesLike,
      extMinExperience: BytesLike,
      extMinEducation: BytesLike,
      extPreferredSex: BytesLike,
      attestation: BytesLike,
      applicationDeadline: BigNumberish,
      vacancyCount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "evaluateAllApplicants"
  ): TypedContractMethod<
    [jobId: BigNumberish, applicants: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "individuals"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, string, string, bigint, boolean] & {
        expectedSalary: string;
        experience: string;
        education: string;
        sex: string;
        contactEmail: string;
        contactPhone: string;
        version: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "jobs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        company: string;
        title: string;
        location: string;
        workPreference: bigint;
        primaryField: bigint;
        maxSalary: string;
        minExperience: string;
        minEducation: string;
        preferredSex: string;
        applicationDeadline: bigint;
        vacancyCount: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextJobId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerCompany"
  ): TypedContractMethod<
    [
      name: string,
      industry: string,
      website: string,
      contactEmail: string,
      location: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerIndividual"
  ): TypedContractMethod<
    [
      extSalary: BytesLike,
      extExperience: BytesLike,
      extEducation: BytesLike,
      extSex: BytesLike,
      extContactEmail: BytesLike,
      extContactPhone: BytesLike,
      attestation: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateCompanyProfile"
  ): TypedContractMethod<
    [
      name: string,
      industry: string,
      website: string,
      contactEmail: string,
      location: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateIndividualProfile"
  ): TypedContractMethod<
    [
      extSalary: BytesLike,
      extExperience: BytesLike,
      extEducation: BytesLike,
      extSex: BytesLike,
      extContactEmail: BytesLike,
      extContactPhone: BytesLike,
      attestation: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ApplicantEvaluated"
  ): TypedContractEvent<
    ApplicantEvaluatedEvent.InputTuple,
    ApplicantEvaluatedEvent.OutputTuple,
    ApplicantEvaluatedEvent.OutputObject
  >;
  getEvent(
    key: "ApplicationSubmitted"
  ): TypedContractEvent<
    ApplicationSubmittedEvent.InputTuple,
    ApplicationSubmittedEvent.OutputTuple,
    ApplicationSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "CompanyProfileUpdated"
  ): TypedContractEvent<
    CompanyProfileUpdatedEvent.InputTuple,
    CompanyProfileUpdatedEvent.OutputTuple,
    CompanyProfileUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CompanyRegistered"
  ): TypedContractEvent<
    CompanyRegisteredEvent.InputTuple,
    CompanyRegisteredEvent.OutputTuple,
    CompanyRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "IndividualProfileUpdated"
  ): TypedContractEvent<
    IndividualProfileUpdatedEvent.InputTuple,
    IndividualProfileUpdatedEvent.OutputTuple,
    IndividualProfileUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "IndividualRegistered"
  ): TypedContractEvent<
    IndividualRegisteredEvent.InputTuple,
    IndividualRegisteredEvent.OutputTuple,
    IndividualRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "JobCreated"
  ): TypedContractEvent<
    JobCreatedEvent.InputTuple,
    JobCreatedEvent.OutputTuple,
    JobCreatedEvent.OutputObject
  >;

  filters: {
    "ApplicantEvaluated(uint256,address)": TypedContractEvent<
      ApplicantEvaluatedEvent.InputTuple,
      ApplicantEvaluatedEvent.OutputTuple,
      ApplicantEvaluatedEvent.OutputObject
    >;
    ApplicantEvaluated: TypedContractEvent<
      ApplicantEvaluatedEvent.InputTuple,
      ApplicantEvaluatedEvent.OutputTuple,
      ApplicantEvaluatedEvent.OutputObject
    >;

    "ApplicationSubmitted(uint256,address)": TypedContractEvent<
      ApplicationSubmittedEvent.InputTuple,
      ApplicationSubmittedEvent.OutputTuple,
      ApplicationSubmittedEvent.OutputObject
    >;
    ApplicationSubmitted: TypedContractEvent<
      ApplicationSubmittedEvent.InputTuple,
      ApplicationSubmittedEvent.OutputTuple,
      ApplicationSubmittedEvent.OutputObject
    >;

    "CompanyProfileUpdated(address,string)": TypedContractEvent<
      CompanyProfileUpdatedEvent.InputTuple,
      CompanyProfileUpdatedEvent.OutputTuple,
      CompanyProfileUpdatedEvent.OutputObject
    >;
    CompanyProfileUpdated: TypedContractEvent<
      CompanyProfileUpdatedEvent.InputTuple,
      CompanyProfileUpdatedEvent.OutputTuple,
      CompanyProfileUpdatedEvent.OutputObject
    >;

    "CompanyRegistered(address,string)": TypedContractEvent<
      CompanyRegisteredEvent.InputTuple,
      CompanyRegisteredEvent.OutputTuple,
      CompanyRegisteredEvent.OutputObject
    >;
    CompanyRegistered: TypedContractEvent<
      CompanyRegisteredEvent.InputTuple,
      CompanyRegisteredEvent.OutputTuple,
      CompanyRegisteredEvent.OutputObject
    >;

    "IndividualProfileUpdated(address,uint32)": TypedContractEvent<
      IndividualProfileUpdatedEvent.InputTuple,
      IndividualProfileUpdatedEvent.OutputTuple,
      IndividualProfileUpdatedEvent.OutputObject
    >;
    IndividualProfileUpdated: TypedContractEvent<
      IndividualProfileUpdatedEvent.InputTuple,
      IndividualProfileUpdatedEvent.OutputTuple,
      IndividualProfileUpdatedEvent.OutputObject
    >;

    "IndividualRegistered(address)": TypedContractEvent<
      IndividualRegisteredEvent.InputTuple,
      IndividualRegisteredEvent.OutputTuple,
      IndividualRegisteredEvent.OutputObject
    >;
    IndividualRegistered: TypedContractEvent<
      IndividualRegisteredEvent.InputTuple,
      IndividualRegisteredEvent.OutputTuple,
      IndividualRegisteredEvent.OutputObject
    >;

    "JobCreated(uint256,address,string)": TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
    JobCreated: TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
  };
}
